
declare module "crypto-js"
declare module "qs"
declare module "js-cookie"
declare module "nprogress"
declare module "@/settings.js"
declare module "vue-echarts"
declare module "@/icons"
declare module "@/permission"
declare module "moment"